### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by karlmikko** [mostafah/pdf.go#1]
Hi Mostafah,

I was looking at making such a library also. I come from a php background but love the speed and concurrency that go offers. I was looking at porting TCPDF as a starting point. However i think there are many things in the go standard lib that could be utilized.

I was wondering if you wanted to help on such a project?

Karl

**Comment by mostafah** [comment]
Thanks for your interest. I'm sure someday I'll start working on this project again, but this is not active right now. Feel free to fork and ask me any questions you may have. A serious progress can make me start working on this again!

BTW, have you also seen [gopdf](https://bitbucket.org/zombiezen/gopdf)?
